name: e_commerce_application
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1


  #--------[PACKAGES]------------
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.0+3
  iconsax: ^0.0.8
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  readmore: ^3.0.0
  uuid: ^4.5.2
  flutter_branch_sdk: ^8.5.0
  razorpay_flutter: ^1.4.1




  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^6.2.1
  connectivity_plus: ^7.0.0
  image_picker: ^1.2.1
  firebase_storage: ^13.0.6




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  #--------[ASSETS]------------
  assets:
    - assets/logo/
    - assets/animations/
    - assets/images/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/banners/
    - assets/products/
    - assets/brands/
#    - assets/icons/payment_methods/


  #--------[FONTS]------------
  fonts:
    - family: 'Nunito'
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800


flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image_dark: assets/logo/black_app_logo.png
  image: assets/logo/white_app_logo.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    image_dark: assets/logo/black_app_logo.png
    image: assets/logo/white_app_logo.png

  web: false

flutter_launcher_icons:
  android: true
  ios: true
  android_round: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_background_dark: "#000000"
  adaptive_icon_foreground: "assets/logo/app_logo_light.png"
  adaptive_icon_foreground_dark: "assets/logo/app_logo_dark.png"
  image_path_android: "assets/logo/app_logo_light.png"
  image_path_ios: "assets/logo/app_logo_light.png"
